# The language in this case has no bearing - we are going to be making use of conda.
language: generic

os: osx

# Set BINSTAR_TOKEN
env:
    matrix:
        - CONFIG=osx_py36
        - CONFIG=osx_py37
    global:
        secure: "Rv7ehFXmCqyWsFjh0v3tIPS4II87wcseL+oMGlEzllGBu+e356yiIjghTD+lEA/Bmv6kihXN0KpD51MZ4YxPJsMGYxnciFJ2Ytmneb9GyDyX7WXY/NlzC0TVDscpFL0iCYep4kkrvysDJawN79h5PO/TShqGnTlKXQ/YRhREMIJpOcPtTHIXH5dB1NmAPXvcNtsFxl8UDrLEFcrWJWchC74cBvqaHFrXcRonbikHz0dZR0q1d01c6dNuFeNZUjBkWR2m1uCZ7kH4hGg+NoffoDt/hPrXaka3VVHomgTkrOKhuQaxpoOgZ86FKJ4Al0SQOfo1EbgGpywayHqeQNJ9zo4FfoWP6Jhf/5aZmG/h8GcatorPRjAwL91yPGtvCSAmE71QgAxRuXUGtz3ZuBUjMUCiIu2csMZDsal6cHbg9eht0psld9o9GCpGZ86rgT8ktYSq+niwpMLPbBMIyuNMxQiZwNwr/PhjGVeb5npik+LcDghjGm0JTTnK+y9hbkoVCk7SC/4FPCiUg0WB6umpQG7HbCNKdpz3ziKtjGsQHlhAmkDe7kLzB41sJjKIdEXJ2M4F2iRtuur+PQ3jpDgqR3Cpk7pHs/IAZXKAH/7HXsyFn9ga9cE0t2wt6ObEIHAkk+W2bksqSkk9y7JW52Cv1j7YjoVVYdoDidZpEabaDPY="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    # Install Miniconda.
    - ./install_miniconda.sh

script:
    - source ~/miniconda/bin/activate base
    - conda build -m build_config/${CONFIG}.yaml ./recipe
    # from https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py
    - ./upload_or_check_non_existence -m build_config/${CONFIG}.yaml ./recipe sebp --channel=main
